### ISSUE TITLE
Not compatible with ligatures

### ISSUE THREAD

**Issue by fzzr-** [CoenraadS/BracketPair#16]
On screencast settings - `"bracketPairColorizer.timeOut": 1000`.

![color-brackets issue mov](https://cloud.githubusercontent.com/assets/888526/24385419/ba8613a6-1372-11e7-8853-2b53e8de13da.gif)

Config:

```json
"bracketPairColorizer.independentPairColors": [
    [
        "()",
        [
            "",
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "#CC3E44"
    ],
    [
        "[]",
        [
            "",
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "#CC3E44"
    ],
    [
        "{}",
        [
            "",
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        "#CC3E44"
    ],
    [
        "<>",
        [
            "",
            "Gold",
            "Orchid",
            "LightSkyBlue"
        ],
        ""
        // "Red"
    ]
]
```

**Comment by CoenraadS** [comment]
Thanks for the report. I'm currently busy with my exams but hope to resume this project sometime next month.

**Comment by CoenraadS** [comment]
Should be fixed in 0.10.1

Thanks for including your settings, it seems empty colors broke it for some reason.

**Comment by fzzr-** [comment]
Wow! Empty colors is a dirty hack but works cool - it adds the css-class `""` (empty) to the DOM-element and then do nothing.

**Comment by M-Zuber** [comment]
I am still seeing issues with this. Different combinations of settings allow some ligatures to work, but others break
config:

**Comment by M-Zuber** [comment]
additional info:
![image](https://user-images.githubusercontent.com/4746537/28174084-1cdb112a-67f9-11e7-94c7-29b45de331b6.png)
The first bracket marked with green matches the `=>` in the function call, and then the bracket marked with blue (which is the real match) is marked red due to being "un-matched"

(This is a `.vue` file, but I have seen the same behavior in regular files as well
