### ISSUE TITLE
not working correctly in nunjucks tpl files after update

### ISSUE THREAD

**Issue by mirino83** [CoenraadS/BracketPair#81]
the extension not working correctly in nunjucks (templating language for JavaScript) tpl files (html language mode setup in VSCode) after update

Before update (v0.10.16)
![bracket-colorizer-v0 10 16](https://user-images.githubusercontent.com/3898424/36901606-0dc71482-1e28-11e8-9791-373391938045.png)

After update (v1.0.14)
![bracket-colorizer-v1 0 14](https://user-images.githubusercontent.com/3898424/36901607-0de1bb20-1e28-11e8-970a-83a8e49f9c1d.png)

**Comment by CoenraadS** [comment]
Thanks for the report, fixed in 1.0.15

**Comment by CoenraadS** [comment]
Oh I just saw this also is about tpl. Could you provide more info about what that is?

**Comment by mirino83** [comment]
still not working correctly

after update (v1.0.15)
![v1 0 15](https://user-images.githubusercontent.com/3898424/36959257-6d2faa5e-2041-11e8-8bae-a55c88044b32.png)

I use **HTML language mode** for the tpl files.

VSCODE
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by CoenraadS** [comment]
Hi

Is there a reason not to use the [Nunjucks](https://marketplace.visualstudio.com/items?itemName=ronnidc.nunjucks) extension? In HTML mode it indeed won't work

**Comment by mirino83** [comment]
But it did work ;-)

I use HTML mode because I use html code inside tpl files and I think VSCode behaves better with this HTML mode turned on when writing html code

but overall this issue is not mandatory for me, I just wanted to point out that I noticed some difference in behaviour when I updated this extension ... 

but if you decide it won´t work with the HTML mode, I´m ok with it ...

**Comment by CoenraadS** [comment]
You can install v0.10.8 from https://github.com/CoenraadS/BracketPair/releases which still has the old behaviour. Thanks for pointing out the changes
