### ISSUE TITLE
Prism.languages.extend is not a function 

### ISSUE THREAD

**Issue by PixelT** [CoenraadS/BracketPair#98]
_@CoenraadS Edit:
A temporary workaround is to disable the `Subtle Match Brackets` extension, or install an older version of the bracket pair extension: https://github.com/CoenraadS/BracketPair/releases/tag/v1.0.20_ 

Original issue:

After update extension to version `1.0.21` I have a notification:
`BracketPair Settings: Prism.languages.extend is not a function`

**Comment by CoenraadS** [comment]
Hmm I will roll back the previous release and investigate this evening

**Comment by PixelT** [comment]
Now I have also
`BracketPair Settings: Prism.languages.insertBefore is not a function`

**Comment by CoenraadS** [comment]
Could you tell me which language this error occurs with?

**Comment by PixelT** [comment]
PHP

**Comment by CoenraadS** [comment]
![image](https://user-images.githubusercontent.com/5593825/37772196-305728f4-2dda-11e8-925b-dc794990bd6f.png)

Could you try uninstalling the marketplace version and installing this version: https://github.com/CoenraadS/BracketPair/releases/download/v1.0.21/bracket-pair-colorizer-1.0.21.vsix

**Comment by PixelT** [comment]
Still have this error, in SCSS files too.

**Comment by CoenraadS** [comment]
I can't reproduce unfortunately

**Comment by PixelT** [comment]
I installed `1.0.22` as update and now it seems to doesn't display this notification, so maybe you are right that there are some problems with cache

**Comment by CoenraadS** [comment]
1.22 is the same as 1.20 it's just has different version number

**Comment by PixelT** [comment]
OK, after update to `1.0.26` I still see that notification :P

**Comment by PixelT** [comment]
Can you release version `1.0.20` as you did it above with version `1.0.21`? I will install as VSIX and check if in this version the notification exist

**Comment by CoenraadS** [comment]
Here is the old version: https://github.com/CoenraadS/BracketPair/releases/tag/v1.0.20

**Comment by PixelT** [comment]
I checked it.

Can you test what happens if you go to %USERPROFILE%/.vscode/extensions and delete all bracket pair folders? Then reinstall the extension?

Didn't help

With version 1.0.20 it works ok, the notification appears on version >=1.0.21so I guess the reason is on changes between v20 and 21

**Comment by hhking** [comment]
![image](https://user-images.githubusercontent.com/11470599/37814578-a1a3d504-2ea5-11e8-8a45-cbfc5cb04356.png)

I update the extension and it also happen to me. The extension doesn't work for me now!

**Comment by CoenraadS** [comment]
If you toggle developer tools (under help menu) and write `process.versions` in the console, what is the version of node?

**Comment by hhking** [comment]
process.version: v7.9.0
vscode: 1.21.1
system: macOS High Sierra 10.13

**Comment by CoenraadS** [comment]
hmm I think @asliabir also used macOS, @PixelT are you also on macOS?

**Comment by PixelT** [comment]
yes, I'm on macOS and I also have `node: "7.9.0"`

**Comment by infinisuite** [comment]
I'm on macOS and I'm getting this as well.
- Node v8.5
- MacOS: 10.13.3
- VS Code: v 1.21.1

**Comment by CaFoHa** [comment]
Same issue on Windows 10

**Comment by asliabir** [comment]
No, I am using Ubuntu 17.10.
and node version is 7.9.0 @CoenraadS

**Comment by CoenraadS** [comment]
Yes! I figured it out. It is conflicted with other extensions using PrismJs. Probably you guys also have the `Subtle Match Brackets` extension installed. Disabling that will make mine work again.

I will investigate possibilities to make them play nicely.

**Comment by CoenraadS** [comment]
Should be fixed in v1.0.27

**Comment by balazser** [comment]
I don't have `Subtle Match Brackets` extension install but still get this error.
